#!/bin/bash
# Just Cause 2 Multiplayer
# Server Management Script
# Author: Mauro ( sodierlou )
# Website: http://rghdcom.it
# Version: 01

#--- VARIABILI

# Dettagli Server
gamename="Just Cause 2 Multiplayer"
servicename="Jcmp-Server"

# Steam login
steamuser="anonymous"
steampass=""

# Steam Appid
appid="261140"

# Direttive
rootdir="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd )"
selfname="$0"
filesdir="${rootdir}/serverfiles"
systemdir="${filesdir}"
executabledir="${filesdir}"
executable="./Jcmp-Server"
servercfgdir="${filesdir}"
servercfg="config.lua"
servercfgfullpath="${servercfgdir}/${servercfg}"
defaultcfg="${servercfgdir}/default-config.lua"
backupdir="backups"
steamclient="${rootdir}/steamcmd/linux32/steamclient.so"




#--- SCRIPT
# Non modificare
# a meno che tu non sappia
# quello che fai


## Controllo Utente
fn_rootcheck(){
if [ `whoami` = "root" ];then
	echo -e "[\e[0;31m FAIL \e[0;39m] Non puoi eseguirlo come utente root!"
	exit
fi
}

## Installazione SteamCMD
fn_steamdl(){
echo "Installazione SteamCMD"
echo "================================="
cd "${rootdir}"
mkdir -pv "steamcmd"
sleep 1
cd "steamcmd"
if [ ! -f steamcmd.sh ]; then
	wget http://media.steampowered.com/client/steamcmd_linux.tar.gz
	tar --verbose -zxf steamcmd_linux.tar.gz
	rm -v steamcmd_linux.tar.gz
	chmod +x steamcmd.sh
	sleep 1
else
	echo ""
	echo "Steam e' gia' installato!"
fi
sleep 1
echo ""
}

